spring.application.name=tools-api-dev

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tools_dev}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Server
# ===============================
server.port=${SERVER_PORT:8083}
server.servlet.context-path=/api/v3

# ===============================
# Logging (DEV = utile)
# ===============================
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.fr.huiitre.tools=DEBUG
logging.level.org.apache.catalina=WARN
logging.level.org.apache.tomcat=WARN
logging.level.org.apache.coyote=WARN
spring.main.log-startup-info=false

# temporaire
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# Dev tools
# ===============================
spring.devtools.restart.enabled=true

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none

# ===============================
# Internal services
# ===============================
tools.services.host=http://localhost:3002

# ===============================
# JWT
# ===============================
security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-ttl=900
security.jwt.refresh-token-ttl=604800
security.jwt.issuer=tools-api
security.cookie.secure=false

# ===============================
# SPRINGDOC API
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# Security CSP
# ===============================
security.csp.policy=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data: